/**
 * Generic Porta;
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserDTO } from './userDTO';


export interface CustomObjectResultListUserDTO {
    value?: Array<UserDTO>;
    declaredType?: string;
    statusCode?: CustomObjectResultListUserDTO.StatusCodeEnum;
}
export namespace CustomObjectResultListUserDTO {
    export type StatusCodeEnum = 100 | 101 | 200 | 201 | 202 | 203 | 204 | 205 | 206 | 300 | 301 | 302 | 303 | 304 | 305 | 306 | 307 | 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 426 | 500 | 501 | 502 | 503 | 504 | 505;
    export const StatusCodeEnum = {
        NUMBER_100: 100 as StatusCodeEnum,
        NUMBER_101: 101 as StatusCodeEnum,
        NUMBER_200: 200 as StatusCodeEnum,
        NUMBER_201: 201 as StatusCodeEnum,
        NUMBER_202: 202 as StatusCodeEnum,
        NUMBER_203: 203 as StatusCodeEnum,
        NUMBER_204: 204 as StatusCodeEnum,
        NUMBER_205: 205 as StatusCodeEnum,
        NUMBER_206: 206 as StatusCodeEnum,
        NUMBER_300: 300 as StatusCodeEnum,
        NUMBER_301: 301 as StatusCodeEnum,
        NUMBER_302: 302 as StatusCodeEnum,
        NUMBER_303: 303 as StatusCodeEnum,
        NUMBER_304: 304 as StatusCodeEnum,
        NUMBER_305: 305 as StatusCodeEnum,
        NUMBER_306: 306 as StatusCodeEnum,
        NUMBER_307: 307 as StatusCodeEnum,
        NUMBER_400: 400 as StatusCodeEnum,
        NUMBER_401: 401 as StatusCodeEnum,
        NUMBER_402: 402 as StatusCodeEnum,
        NUMBER_403: 403 as StatusCodeEnum,
        NUMBER_404: 404 as StatusCodeEnum,
        NUMBER_405: 405 as StatusCodeEnum,
        NUMBER_406: 406 as StatusCodeEnum,
        NUMBER_407: 407 as StatusCodeEnum,
        NUMBER_408: 408 as StatusCodeEnum,
        NUMBER_409: 409 as StatusCodeEnum,
        NUMBER_410: 410 as StatusCodeEnum,
        NUMBER_411: 411 as StatusCodeEnum,
        NUMBER_412: 412 as StatusCodeEnum,
        NUMBER_413: 413 as StatusCodeEnum,
        NUMBER_414: 414 as StatusCodeEnum,
        NUMBER_415: 415 as StatusCodeEnum,
        NUMBER_416: 416 as StatusCodeEnum,
        NUMBER_417: 417 as StatusCodeEnum,
        NUMBER_426: 426 as StatusCodeEnum,
        NUMBER_500: 500 as StatusCodeEnum,
        NUMBER_501: 501 as StatusCodeEnum,
        NUMBER_502: 502 as StatusCodeEnum,
        NUMBER_503: 503 as StatusCodeEnum,
        NUMBER_504: 504 as StatusCodeEnum,
        NUMBER_505: 505 as StatusCodeEnum
    }
}
