/**
 * Generic Porta;
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EventDTO {
    date?: Date;
    title?: string;
    description?: string;
    phoneNumber?: string;
    website?: string;
    address?: string;
    imageUrl?: string;
    iconUrl?: string;
    openingHours?: string;
    longitude?: number;
    latitude?: number;
    distance?: number;
    id?: string;
}
