/**
 * Generic Porta;
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Interest {
    name?: string;
    description?: string;
    iconUrl?: string;
    type?: string;
    id?: string;
    version?: string;
    createdAt?: Date;
    updatedAt?: Date;
    deleted?: boolean;
}
