/**
 * Generic Porta;
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NotificationSecondaryTile } from './notificationSecondaryTile';
import { NotificationTemplate } from './notificationTemplate';


export interface NotificationInstallation {
    pushChannel: string;
    platform: string;
    installationId?: string;
    templates?: { [key: string]: NotificationTemplate; };
    secondaryTiles?: { [key: string]: NotificationSecondaryTile; };
    tags?: Array<string>;
}
