/**
 * Generic Porta;
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserDTO {
    sid?: string;
    email?: string;
    facebookId?: string;
    firstName?: string;
    lastName?: string;
    profilePictureUrl?: string;
    bio?: string;
    address?: string;
    occupation?: string;
    maternalStatus?: string;
    gender?: string;
    DOB?: Date;
    facebookSmallProfilePictureUrl?: string;
    facebookCoverPictureUrl?: string;
    facebookLink?: string;
    akukuVerified?: boolean;
    facebookVerified?: boolean;
    signupProvider?: string;
    profileComplete?: boolean;
    childrenAsString?: string;
    mumInterestsAsString?: string;
    outsideInterestsAsString?: string;
    longitude?: number;
    latitude?: number;
    distance?: number;
    id?: string;
}
