/**
 * Generic Porta;
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DbGeography } from './dbGeography';
import { Interest } from './interest';
import { UserChild } from './userChild';


export interface User {
    sid?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    profilePictureUrl?: string;
    bio?: string;
    address?: string;
    occupation?: string;
    maternalStatus?: string;
    gender?: string;
    DOB?: Date;
    passwordHash?: string;
    salt?: string;
    akukuVerified?: boolean;
    moderationStatus?: string;
    profileComplete?: boolean;
    signupProvider?: string;
    facebookSmallProfilePictureUrl?: string;
    facebookCoverPictureUrl?: string;
    facebookUserAccessToken?: string;
    facebookLink?: string;
    facebookVerified?: boolean;
    facebookId?: string;
    childrenAsString?: string;
    mumInterestsAsString?: string;
    outsideInterestsAsString?: string;
    children?: Array<UserChild>;
    maternalInterest?: Array<Interest>;
    generalInterest?: Array<Interest>;
    longitude?: number;
    latitude?: number;
    location?: DbGeography;
    distance?: number;
    id?: string;
    version?: string;
    createdAt?: Date;
    updatedAt?: Date;
    deleted?: boolean;
}
