export * from './customAuth.service';
import { CustomAuthService } from './customAuth.service';
export * from './events.service';
import { EventsService } from './events.service';
export * from './getStorageToken.service';
import { GetStorageTokenService } from './getStorageToken.service';
export * from './item.service';
import { ItemService } from './item.service';
export * from './notificationInstallations.service';
import { NotificationInstallationsService } from './notificationInstallations.service';
export * from './places.service';
import { PlacesService } from './places.service';
export * from './placesAdmin.service';
import { PlacesAdminService } from './placesAdmin.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './userConfig.service';
import { UserConfigService } from './userConfig.service';
export const APIS = [CustomAuthService, EventsService, GetStorageTokenService, ItemService, NotificationInstallationsService, PlacesService, PlacesAdminService, UserService, UserConfigService];
