/**
 * Generic Porta;
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { StorageTokenViewModel } from '../model/storageTokenViewModel';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class GetStorageTokenService {

    protected basePath = 'https://genericportalbackend.azurewebsites.net';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param ZUMO_API_VERSION 
     * @param X_ZUMO_AUTH 
     * @param fileExtension 
     * @param filePrefix 
     * @param virtualSubDirectory 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getStorageTokenGetAsync(ZUMO_API_VERSION: string, X_ZUMO_AUTH: string, fileExtension?: string, filePrefix?: string, virtualSubDirectory?: string, observe?: 'body', reportProgress?: boolean): Observable<StorageTokenViewModel>;
    public getStorageTokenGetAsync(ZUMO_API_VERSION: string, X_ZUMO_AUTH: string, fileExtension?: string, filePrefix?: string, virtualSubDirectory?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<StorageTokenViewModel>>;
    public getStorageTokenGetAsync(ZUMO_API_VERSION: string, X_ZUMO_AUTH: string, fileExtension?: string, filePrefix?: string, virtualSubDirectory?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<StorageTokenViewModel>>;
    public getStorageTokenGetAsync(ZUMO_API_VERSION: string, X_ZUMO_AUTH: string, fileExtension?: string, filePrefix?: string, virtualSubDirectory?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (ZUMO_API_VERSION === null || ZUMO_API_VERSION === undefined) {
            throw new Error('Required parameter ZUMO_API_VERSION was null or undefined when calling getStorageTokenGetAsync.');
        }
        if (X_ZUMO_AUTH === null || X_ZUMO_AUTH === undefined) {
            throw new Error('Required parameter X_ZUMO_AUTH was null or undefined when calling getStorageTokenGetAsync.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (fileExtension !== undefined) {
            queryParameters = queryParameters.set('fileExtension', <any>fileExtension);
        }
        if (filePrefix !== undefined) {
            queryParameters = queryParameters.set('filePrefix', <any>filePrefix);
        }
        if (virtualSubDirectory !== undefined) {
            queryParameters = queryParameters.set('virtualSubDirectory', <any>virtualSubDirectory);
        }

        let headers = this.defaultHeaders;
        if (ZUMO_API_VERSION !== undefined && ZUMO_API_VERSION !== null) {
            headers = headers.set('ZUMO-API-VERSION', String(ZUMO_API_VERSION));
        }
        if (X_ZUMO_AUTH !== undefined && X_ZUMO_AUTH !== null) {
            headers = headers.set('X-ZUMO-AUTH', String(X_ZUMO_AUTH));
        }

        // authentication (facebook) required
        if (this.configuration.accessToken) {
            let accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<StorageTokenViewModel>(`${this.basePath}/api/GetStorageToken`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
