/**
 * Generic Porta;
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { NotificationInstallation } from '../model/notificationInstallation';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class NotificationInstallationsService {

    protected basePath = 'https://genericportalbackend.azurewebsites.net';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param installationId 
     * @param ZUMO_API_VERSION 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public notificationInstallationsDeleteInstallation(installationId: string, ZUMO_API_VERSION: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public notificationInstallationsDeleteInstallation(installationId: string, ZUMO_API_VERSION: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public notificationInstallationsDeleteInstallation(installationId: string, ZUMO_API_VERSION: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public notificationInstallationsDeleteInstallation(installationId: string, ZUMO_API_VERSION: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (installationId === null || installationId === undefined) {
            throw new Error('Required parameter installationId was null or undefined when calling notificationInstallationsDeleteInstallation.');
        }
        if (ZUMO_API_VERSION === null || ZUMO_API_VERSION === undefined) {
            throw new Error('Required parameter ZUMO_API_VERSION was null or undefined when calling notificationInstallationsDeleteInstallation.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (installationId !== undefined) {
            queryParameters = queryParameters.set('installationId', <any>installationId);
        }

        let headers = this.defaultHeaders;
        if (ZUMO_API_VERSION !== undefined && ZUMO_API_VERSION !== null) {
            headers = headers.set('ZUMO-API-VERSION', String(ZUMO_API_VERSION));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/NotificationInstallations`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param installationId 
     * @param notificationInstallation 
     * @param ZUMO_API_VERSION 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public notificationInstallationsPutInstallation(installationId: string, notificationInstallation: NotificationInstallation, ZUMO_API_VERSION: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public notificationInstallationsPutInstallation(installationId: string, notificationInstallation: NotificationInstallation, ZUMO_API_VERSION: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public notificationInstallationsPutInstallation(installationId: string, notificationInstallation: NotificationInstallation, ZUMO_API_VERSION: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public notificationInstallationsPutInstallation(installationId: string, notificationInstallation: NotificationInstallation, ZUMO_API_VERSION: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (installationId === null || installationId === undefined) {
            throw new Error('Required parameter installationId was null or undefined when calling notificationInstallationsPutInstallation.');
        }
        if (notificationInstallation === null || notificationInstallation === undefined) {
            throw new Error('Required parameter notificationInstallation was null or undefined when calling notificationInstallationsPutInstallation.');
        }
        if (ZUMO_API_VERSION === null || ZUMO_API_VERSION === undefined) {
            throw new Error('Required parameter ZUMO_API_VERSION was null or undefined when calling notificationInstallationsPutInstallation.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (installationId !== undefined) {
            queryParameters = queryParameters.set('installationId', <any>installationId);
        }

        let headers = this.defaultHeaders;
        if (ZUMO_API_VERSION !== undefined && ZUMO_API_VERSION !== null) {
            headers = headers.set('ZUMO-API-VERSION', String(ZUMO_API_VERSION));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/api/NotificationInstallations`,
            notificationInstallation,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
