/**
 * Generic Porta;
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class UserConfigService {

    protected basePath = 'https://genericportalbackend.azurewebsites.net';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param facebookAccessToken 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public userConfigGetFacebookUser(facebookAccessToken: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public userConfigGetFacebookUser(facebookAccessToken: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public userConfigGetFacebookUser(facebookAccessToken: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public userConfigGetFacebookUser(facebookAccessToken: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (facebookAccessToken === null || facebookAccessToken === undefined) {
            throw new Error('Required parameter facebookAccessToken was null or undefined when calling userConfigGetFacebookUser.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (facebookAccessToken !== undefined) {
            queryParameters = queryParameters.set('facebookAccessToken', <any>facebookAccessToken);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/api/userconfig/facebookuser`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param userId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public userConfigGetFacebookUserProfilePic(userId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public userConfigGetFacebookUserProfilePic(userId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public userConfigGetFacebookUserProfilePic(userId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public userConfigGetFacebookUserProfilePic(userId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling userConfigGetFacebookUserProfilePic.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/api/userconfig/facebookuser/${encodeURIComponent(String(userId))}/profilepic`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param azureAccessToken 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public userConfigGetSocialUser(azureAccessToken: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public userConfigGetSocialUser(azureAccessToken: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public userConfigGetSocialUser(azureAccessToken: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public userConfigGetSocialUser(azureAccessToken: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (azureAccessToken === null || azureAccessToken === undefined) {
            throw new Error('Required parameter azureAccessToken was null or undefined when calling userConfigGetSocialUser.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (azureAccessToken !== undefined) {
            queryParameters = queryParameters.set('azureAccessToken', <any>azureAccessToken);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/api/userconfig/socialuser`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
